# Generated by Django 4.2.2 on 2023-06-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="hobby",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
