# Generated by Django 4.2.2 on 2023-07-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_person_hobby"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="dick_length",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
